import datetime
import os
import sys

import pytest

import sys
from pathlib import Path

# tests/utils/ sits two levels above this conftest
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from utils.ylwa_writer import YlwaWriter  # noqa: E402

BENCHMARK_RESULTS = []


def pytest_addoption(parser):
    parser.addoption(
        "--benchmark",
        action="store_true",
        default=False,
        help="Run benchmarks and save results to benchmark_python.ylwa",
    )


@pytest.fixture
def benchmark_collector(pytestconfig):
    """Fixture to collect benchmark results during tests."""
    enabled = pytestconfig.getoption("--benchmark")

    class Collector:
        @property
        def is_enabled(self):
            return enabled

        def add(self, file_path, phase, duration, mem_delta):
            if enabled:
                BENCHMARK_RESULTS.append({
                    "file": str(file_path),
                    "phase": phase,
                    "time": duration,
                    "memory_delta": mem_delta,
                })

    return Collector()


def pytest_sessionfinish(session, exitstatus):
    if not (session.config.getoption("--benchmark") and BENCHMARK_RESULTS):
        return

    writer = YlwaWriter()
    writer.add_header("Yumly Python Benchmark Results")
    writer.add_comment(
        f"Generated by Yumly Python Test Runner\n"
        f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    for res in BENCHMARK_RESULTS:
        writer.begin_block("Benchmark")
        writer.add_field("File", res["file"])
        writer.add_field("Phase", res["phase"])
        writer.add_field("Time", f"{res['time']}s")
        writer.add_field("Memory Delta", f"{res['memory_delta']}MB")
        writer.end_block()

    with open("benchmark_python.ylwa", "w") as f:
        f.write(writer.to_string())

    tr = session.config.pluginmanager.get_plugin("terminalreporter")
    if tr:
        tr.write_line("\n📊 Benchmark results saved to benchmark_python.ylwa")