[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yumly"
version = "0.10.0"
description = "A cute, declarative config language with fail-fast behavior and optional type safety."
readme = "README.MD"
authors = [{ name = "Yumene", email = "yumene@yume.dev.br" }]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"

[tool.setuptools]
packages = ["yumly"]
package-dir = {"" = "src/lib/python"}

[project.urls]
"Homepage" = "https://github.com/Creeper011/Yumly"
"Bug Tracker" = "https://github.com/Creeper011/Yumly/issues"
