[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yumly"
version = "0.8.3"
description = "A cute, declarative config language with fail-fast behavior and optional type safety."
readme = "README.md"
authors = [{ name = "Yumene", email = "yumene@yume.dev.br" }]
license = { file = "LICENSE" }
requires-python = ">=3.10"

[tool.setuptools]
packages = ["yumly"]
package-dir = {"" = "lib/python"}

[tool.setuptools.package-data]
yumly = ["libyumly.so", "libyumly.pyd"]

[project.urls]
"Homepage" = "https://github.com/Creeper011/Yumly"
"Bug Tracker" = "https://github.com/Creeper011/Yumly/issues"