import datetime
import sys
from collections import defaultdict
from pathlib import Path

import pytest

# tests/utils/ sits two levels above this conftest
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from utils.ylwa_writer import YlwaWriter  # noqa: E402

BENCHMARK_RESULTS = []


def pytest_addoption(parser):
    parser.addoption(
        "--benchmark",
        action="store_true",
        default=False,
        help="Run benchmarks and save results to benchmark_python.ylwa",
    )
    parser.addoption(
        "--stress-only",
        action="store_true",
        default=False,
        help="Collect only stress fixtures",
    )


@pytest.fixture
def benchmark_collector(pytestconfig):
    """Fixture to collect benchmark results during tests."""
    enabled = pytestconfig.getoption("--benchmark")

    class Collector:
        @property
        def is_enabled(self):
            return enabled

        def add(self, *, category, test_id, file_path, operation, duration, memory_delta):
            if enabled:
                BENCHMARK_RESULTS.append({
                    "category": str(category),
                    "test_id": str(test_id),
                    "file": str(file_path),
                    "operation": str(operation),
                    "time": duration,
                    "memory_delta": max(0, memory_delta),
                })

    return Collector()


def pytest_sessionfinish(session, exitstatus):
    if not (session.config.getoption("--benchmark") and BENCHMARK_RESULTS):
        return

    writer = YlwaWriter()
    writer.add_comment("Yumly Python Benchmark Results")
    writer.add_comment(
        f"Generated by Yumly Python Test Runner\n"
        f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    def format_time(t):
        if t < 0.001:
            return f"{t * 1_000_000:.1f}us"
        elif t < 1.0:
            return f"{t * 1_000:.1f}ms"
        return f"{t:.2f}s"

    def format_memory(memory):
        return f"{memory:.3f}MB"

    def unique_tests(entries):
        return len({entry["test_id"] for entry in entries})

    def is_stress_test(entry):
        normalized_path = entry["file"].replace("\\", "/")
        return (
            entry["category"] == "fixture"
            and ("/stress/" in normalized_path or entry["test_id"].startswith("s"))
        )

    def fixture_kind(entry):
        normalized_path = entry["file"].replace("\\", "/")
        if is_stress_test(entry):
            return "stress"
        test_id = entry["test_id"]
        if "/invalid/" in normalized_path or test_id.startswith("x"):
            return "invalid"
        if "/valid/" in normalized_path or test_id.startswith("y"):
            return "valid"
        return "unknown"

    def add_summary_fields(entries, split_stress_memory=False):
        if not entries:
            return
        total_time = sum(entry["time"] for entry in entries)
        peak_memory = max(entry["memory_delta"] for entry in entries)
        has_stress_memory = any(is_stress_test(entry) for entry in entries)
        peak_regular_memory = max(
            (
                entry["memory_delta"]
                for entry in entries
                if not is_stress_test(entry)
            ),
            default=0,
        )
        peak_stress_memory = max(
            (
                entry["memory_delta"]
                for entry in entries
                if is_stress_test(entry)
            ),
            default=0,
        )
        slowest = max(entries, key=lambda entry: entry["time"])

        writer.add_field("Tests", str(unique_tests(entries)))
        writer.add_field("Measurements", str(len(entries)))
        writer.add_field("Total Time", format_time(total_time))
        writer.add_field("Average Time", format_time(total_time / len(entries)))
        writer.add_field("Peak Memory Delta", format_memory(peak_memory))
        if split_stress_memory and has_stress_memory:
            writer.add_field(
                "Peak Memory Delta Excluding Stress Tests",
                format_memory(peak_regular_memory),
            )
            writer.add_field(
                "Peak Memory Delta On Stress Tests",
                format_memory(peak_stress_memory),
            )
        writer.add_field(
            "Slowest",
            f"{slowest['operation']} {slowest['test_id']}",
        )

    def add_operation_summaries(entries, split_stress_memory=False):
        if not entries:
            return

        operation_groups = defaultdict(list)
        for entry in entries:
            operation_groups[entry["operation"]].append(entry)

        writer.begin_block("Operation Summaries")
        for operation in sorted(operation_groups):
            measurements = operation_groups[operation]
            operation_time = sum(entry["time"] for entry in measurements)
            operation_memory = max(entry["memory_delta"] for entry in measurements)
            operation_has_stress_memory = any(
                is_stress_test(entry) for entry in measurements
            )
            operation_regular_memory = max(
                (
                    entry["memory_delta"]
                    for entry in measurements
                    if not is_stress_test(entry)
                ),
                default=0,
            )
            operation_stress_memory = max(
                (
                    entry["memory_delta"]
                    for entry in measurements
                    if is_stress_test(entry)
                ),
                default=0,
            )

            writer.begin_block(f"Operation {operation}")
            writer.add_field("Measurements", str(len(measurements)))
            writer.add_field("Total Time", format_time(operation_time))
            writer.add_field(
                "Average Time",
                format_time(operation_time / len(measurements)),
            )
            writer.add_field(
                "Peak Memory Delta",
                format_memory(operation_memory),
            )
            if split_stress_memory and operation_has_stress_memory:
                writer.add_field(
                    "Peak Memory Delta Excluding Stress Tests",
                    format_memory(operation_regular_memory),
                )
                writer.add_field(
                    "Peak Memory Delta On Stress Tests",
                    format_memory(operation_stress_memory),
                )
            writer.end_block()
        writer.end_block()

    def add_benchmarked_tests(entries, block_prefix):
        if not entries:
            return

        test_groups = defaultdict(list)
        for entry in entries:
            test_groups[entry["test_id"]].append(entry)

        for test_id in sorted(test_groups):
            measurements = sorted(
                test_groups[test_id],
                key=lambda entry: entry["operation"],
            )
            total_time = sum(entry["time"] for entry in measurements)
            peak_memory = max(entry["memory_delta"] for entry in measurements)

            writer.begin_block(f"{block_prefix} {test_id}")
            writer.add_field("Test", test_id)
            writer.add_field("File", measurements[0]["file"])
            writer.add_field("Total Time", format_time(total_time))
            writer.add_field("Peak Memory Delta", format_memory(peak_memory))

            for entry in measurements:
                writer.begin_block(f"Operation {entry['operation']}")
                writer.add_field("Time", format_time(entry["time"]))
                writer.add_field(
                    "Memory Delta",
                    format_memory(entry["memory_delta"]),
                )
                writer.end_block()

            writer.end_block()

    def add_unit_benchmarks(entries):
        if not entries:
            return

        writer.begin_block("Unit Benchmarks")
        writer.begin_block("Summary")
        add_summary_fields(entries)
        writer.end_block()
        add_operation_summaries(entries)
        writer.begin_block("Units")
        add_benchmarked_tests(entries, "Unit")
        writer.end_block()
        writer.end_block()

    def add_fixture_benchmarks(entries):
        if not entries:
            return

        fixture_groups = defaultdict(list)
        for entry in entries:
            fixture_groups[fixture_kind(entry)].append(entry)

        writer.begin_block("Fixture Benchmarks")
        for kind in ("valid", "invalid", "stress", "unknown"):
            measurements = fixture_groups.get(kind, [])
            if not measurements:
                continue

            writer.begin_block(f"Group {kind}")
            writer.add_field("Kind", kind)
            writer.begin_block("Summary")
            add_summary_fields(measurements)
            writer.end_block()
            add_operation_summaries(measurements)
            writer.begin_block("Fixtures")
            add_benchmarked_tests(measurements, "Fixture")
            writer.end_block()
            writer.end_block()
        writer.end_block()

    units = [
        entry for entry in BENCHMARK_RESULTS
        if entry["category"] == "unit"
    ]
    fixtures = [
        entry for entry in BENCHMARK_RESULTS
        if entry["category"] == "fixture"
    ]

    writer.begin_block("Summary")
    writer.add_field("Unit Tests", str(unique_tests(units)))
    writer.add_field("Fixture Tests", str(unique_tests(fixtures)))
    add_summary_fields(BENCHMARK_RESULTS, split_stress_memory=True)
    writer.end_block()
    add_operation_summaries(BENCHMARK_RESULTS, split_stress_memory=True)
    add_unit_benchmarks(units)
    add_fixture_benchmarks(fixtures)

    with open("benchmark_python.ylwa", "w") as f:
        f.write(writer.to_string())

    tr = session.config.pluginmanager.get_plugin("terminalreporter")
    if tr:
        tr.write_line("\n📊 Benchmark results saved to benchmark_python.ylwa")
