"""Defines languages"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Language:
    name: str
    extensions: tuple[str, ...] = ()
    filenames: tuple[str, ...] = ()  # Specific filenames without an extension.


BUILTIN_LANGUAGES = (
    Language("Yumly", (".yumly", ".yuy", ".yu")),
    Language("Nim", (".nim", ".nims", ".nimble")),
    Language("Python", (".py", ".pyw", ".pyi")),
    Language("C", (".c", ".h")),
    Language("C++", (".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx")),
    Language("C#", (".cs",)),
    Language("Rust", (".rs",)),
    Language("Zig", (".zig",)),
    Language("Go", (".go",)),
    Language("Java", (".java",)),
    Language("Kotlin", (".kt", ".kts")),
    Language("Scala", (".scala", ".sc")),
    Language("Groovy", (".groovy", ".gradle")),
    Language("Swift", (".swift",)),
    Language("Objective-C", (".m", ".mm")),
    Language("Dart", (".dart",)),
    Language("JavaScript", (".js", ".mjs", ".cjs", ".jsx")),
    Language("TypeScript", (".ts", ".mts", ".cts", ".tsx")),
    Language("Vue", (".vue",)),
    Language("Svelte", (".svelte",)),
    Language("HTML", (".html", ".htm")),
    Language("CSS", (".css",)),
    Language("Sass", (".sass", ".scss")),
    Language("Less", (".less",)),
    Language("Ruby", (".rb",)),
    Language("PHP", (".php",)),
    Language("Lua", (".lua",)),
    Language("Perl", (".pl", ".pm")),
    Language("Raku", (".raku", ".rakumod", ".rakutest")),
    Language("R", (".r",)),
    Language("Julia", (".jl",)),
    Language("Shell", (".sh", ".bash", ".zsh", ".fish")),
    Language("PowerShell", (".ps1", ".psm1", ".psd1")),
    Language("Batch", (".bat", ".cmd")),
    Language("Elixir", (".ex", ".exs")),
    Language("Erlang", (".erl", ".hrl")),
    Language("Haskell", (".hs", ".lhs")),
    Language("OCaml", (".ml", ".mli")),
    Language("F#", (".fs", ".fsi", ".fsx")),
    Language("Clojure", (".clj", ".cljs", ".cljc", ".edn")),
    Language("Common Lisp", (".lisp", ".lsp", ".cl")),
    Language("Scheme", (".scm", ".ss")),
    Language("Racket", (".rkt",)),
    Language("Fortran", (".f", ".f90", ".f95", ".f03", ".f08")),
    Language("Ada", (".ada", ".adb", ".ads")),
    Language("Pascal", (".pas", ".pp")),
    Language("D", (".d",)),
    Language("Assembly", (".asm", ".s")),
    Language("Solidity", (".sol",)),
    Language("SQL", (".sql",)),
    Language("GraphQL", (".graphql", ".gql")),
    Language("Protocol Buffer", (".proto",)),
    Language("Nix", (".nix",)),
    Language("Terraform", (".tf", ".tfvars")),
    Language("HCL", (".hcl",)),
    Language("KDL", (".kdl",)),
    Language("CUE", (".cue",)),
    Language("Dhall", (".dhall",)),
    Language("Jsonnet", (".jsonnet", ".libsonnet")),
    Language("Nickel", (".ncl",)),
    Language("Pkl", (".pkl",)),
    Language("Starlark", (".bzl", ".star"), ("build", "workspace")),
    Language("Dockerfile", (".dockerfile",), ("dockerfile", "containerfile")),
    Language("CMake", (".cmake",), ("cmakelists.txt",)),
    Language("JSON", (".json",), ("flake.lock",)),
    Language("JSON5", (".json5",)),
    Language("JSON with Comments", (".jsonc",)),
    Language("YAML", (".yaml", ".yml")),
    Language("TOML", (".toml",)),
    Language("INI", (".ini", ".cfg")),
    Language("Java Properties", (".properties",)),
    Language("XML", (".xml", ".xsd", ".xsl", ".xslt")),
    Language("Jupyter Notebook", (".ipynb",)),
    Language("EBNF", (".ebnf",)),
    Language("Markdown", (".md", ".markdown")),
    Language("AsciiDoc", (".adoc", ".asciidoc")),
    Language("reStructuredText", (".rst",)),
    Language("TeX", (".tex", ".sty", ".cls")),
    Language("Makefile", filenames=("makefile", "gnumakefile")),
)
