## External representation of Yumly error codes.

import ../types/errors

func `$`*(code: ErrorCode): string =
  case code
  of ecNone: ""
  of ecParserExpected: "parser.expected"
  of ecParserUnexpectedRoot: "parser.unexpected-root"
  of ecParserIncludeOrder: "parser.include-order"
  of ecParserSchemaOrder: "parser.schema-order"
  of ecParserSchemaFile: "parser.schema-file"
  of ecParserSchemaFieldType: "parser.schema-field-type"
  of ecParserObjectContext: "parser.object-context"
  of ecParserIncludeComma: "parser.include-comma"
  of ecParserEnvDisabled: "parser.env-disabled"
  of ecParserRecursionLimit: "parser.recursion-limit"
  of ecResolverUnknownTypeHint: "resolver.unknown-type-hint"
  of ecResolverEnvDisabled: "resolver.env-disabled"
  of ecValidatorDuplicatePair: "validator.duplicate-pair"
  of ecValidatorDuplicateBlock: "validator.duplicate-block"
  of ecValidatorDuplicateSchema: "validator.duplicate-schema"
  of ecValidatorListElementType: "validator.list-element-type"
  of ecValidatorMissingEnv: "validator.missing-env"
  of ecValidatorMultipleErrors: "validator.multiple-errors"
  of ecValidatorTypeMismatch: "validator.type-mismatch"
  of ecValidatorUnknownSchema: "validator.unknown-schema"
  of ecValidatorSchemaMissingField: "validator.schema-missing-field"
  of ecValidatorSchemaUnknownField: "validator.schema-unknown-field"
  of ecValidatorSchemaMissingBlock: "validator.schema-missing-block"
  of ecValidatorSchemaBlockValueType: "validator.schema-block-value-type"
  of ecValidatorRecursionLimit: "validator.recursion-limit"
  of ecValidatorInvalidItemContext: "validator.invalid-item-context"
  of ecIncludeLoadFailed: "include.load-failed"
  of ecIncludeCircularImport: "include.circular"
  of ecIncludeNotFound: "include.not-found"
  of ecIncludeDotenvDisabled: "include.dotenv-disabled"
  of ecIncludeUnsupportedExtension: "include.unsupported-extension"
  of ecIncludeSandboxViolation: "include.sandbox-violation"
  of ecFileInvalidExtension: "file.invalid-extension"
  of ecFileNotFound: "file.not-found"
  of ecFileTooLarge: "file.too-large"
  of ecFileOpenFailed: "file.open-failed"
  of ecTokenizerUnclosedComment: "tokenizer.unclosed-comment"
  of ecTokenizerInvalidExponent: "tokenizer.invalid-exponent"
  of ecTokenizerUnclosedString: "tokenizer.unclosed-string"
  of ecTokenizerUnexpectedCharacter: "tokenizer.unexpected-character"
  of ecEvaluatorInvalidEscape: "evaluator.invalid-escape"
  of ecEvaluatorEnvCoerceFailed: "evaluator.env-coerce-failed"
  of ecEvaluatorInvalidLiteralToken: "evaluator.invalid-literal-token"
  of ecEvaluatorInvalidNodeKind: "evaluator.invalid-node-kind"
  of ecValueInvalidInteger: "value.invalid-integer"
  of ecValueInvalidFloat: "value.invalid-float"
  of ecValueInvalidBoolean: "value.invalid-boolean"
