name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-yumly
        with:
          python-version: ${{ vars.PYTHON_VERSION || '3.12' }}

      - name: Run tests
        run: nimble --nimbleDir:build/nimble checkSources
